= Overview
:extension-status: preview

This extension allows usage of the _HiveMQ MQTT Client_ inside a Quarkus App, in JVM and Native mode.

Together with the https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.4/mqtt/mqtt.html["SmallRye Reactive Messaging MQTT"] extension allows usage of a new connector type *smallrye-mqtt-hivemq* that will use _HiveMQ MQTT Client_ instead of Vertx MQTT client.

This adds some benefits to the original SmallRye MQTT:

* Battle tested MQTT Client outside Vertx landscape
* Management of external CA file for secure connections with self-signed certificates
* Backpressure support integrated with MQTT QOS
* Automatic and configurable reconnection handling and message redelivery
* Real Health Check against a configurable topic (defaults to the standard MQTT $SYS/broker/uptime) integrated in Quarkus HealthReport
* Many others you can read in official documentation https://hivemq.github.io/hivemq-mqtt-client/[here].

== Matrix compatibility

|===
| Quarkus-hivemq-client version | Quarkus version | HiveMQ client version
| 2.0.0
| 3.6.5
| 1.3.3
| 1.1.0
| 2.16.12.Final
| 1.3.3
| 1.0.0
| 2.16.10.Final
| 1.3.2
|===

== Add/use HiveMQ Extension

Requirements:

* Maven 3.8.1+
* JDK 11+ installed with JAVA_HOME configured appropriately

Create a Quarkus application with the HiveMQ-SmallRye extension

```shell
mvn io.quarkus:quarkus-maven-plugin:3.6.5:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=hivemq-quickstart \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello" \
    -Dextensions="resteasy-reactive,hivemq,smallrye-reactive-messaging-mqtt"
cd hivemq-quickstart
```

If you already have your Quarkus project configured, you can add the hivemq extension to your project by running the following command in your project base directory:
```shell
./mvnw quarkus:add-extension -Dextensions="hivemq"
```

This command will add the following dependency to your pom.xml file:

```xml
<dependency>
    <groupId>io.quarkiverse.hivemqclient</groupId>
    <artifactId>quarkus-hivemq-client</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-reactive-messaging-mqtt</artifactId>
</dependency>
```

Then configure your application by adding the HiveMQ connector type:

```
# Inbound
mp.messaging.incoming.[channel-name].connector=smallrye-mqtt-hivemq

# Outbound
mp.messaging.outgoing.[channel-name].connector=smallrye-mqtt-hivemq
```

== How to Subscribe to MQTT Topics?

Let’s imagine you have a HiveMQ broker running, and accessible using the localhost:1883 address. Configure your application to receive MQTT messages on the prices channel as follows:

```
mp.messaging.incoming.prices.connector=smallrye-mqtt-hivemq
mp.messaging.incoming.prices.host=localhost
mp.messaging.incoming.prices.port=1883
mp.messaging.incoming.prices.auto-generated-client-id=true
```

Then, your application receives Message<byte[]>. You can consume the payload directly:

```
package inbound;

import org.eclipse.microprofile.reactive.messaging.Incoming;

import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class MqttPriceConsumer {

    @Incoming("prices")
    public void consume(byte[] raw) {
        double price = Double.parseDouble(new String(raw));

        // process your price.
    }

}
```

If you want a more detailed example, please take a look the following end-to-end link:https://github.com/quarkiverse/quarkus-hivemq-client/tree/main/integration-tests/hivemq-client-smallrye[Test]

== How to Publish to MQTT Topics?

Let's configure the 'outgoing' channel

```
mp.messaging.outgoing.topic-price.connector=smallrye-mqtt-hivemq
mp.messaging.outgoing.topic-price.topic=prices
mp.messaging.outgoing.topic-price.auto-generated-client-id=true
```

And then implement an emitter or producer, for example as this one:

```
package outbound;

import org.eclipse.microprofile.reactive.messaging.Outgoing;

import jakarta.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class PriceGenerator {

    private static final Logger LOG = Logger.getLogger(PriceGenerator.class);

    private Random random = new Random();

    @Outgoing("topic-price")
    public Multi<Integer> generate() {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(1))
                .onOverflow().drop()
                .map(tick -> {
                    int price = random.nextInt(100);
                    LOG.infof("Sending price: %d", price);
                    return price;
                });
    }

}
```


== Configuration Reference

include::config.adoc[leveloffset=+1, opts=optional]
