= Getting Started

:extension-status: preview
include::./includes/attributes.adoc[]

This extension allows usage of the _HiveMQ MQTT Client_ inside a Quarkus App, in JVM and Native mode.

Together with the https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.4/mqtt/mqtt.html["SmallRye Reactive Messaging MQTT"] extension allows usage of a new connector type *smallrye-mqtt-hivemq* that will use _HiveMQ Client_ instead of Vertx MQTT client.

This adds some benefits to the original SmallRye MQTT:

* [*] Battle tested MQTT Client outside Vertx landscape
* [*] Management of external CA file for secure connections with self-signed certificates
* [*] Backpressure support integrated with MQTT QOS
* [*] Native mode support
* [*] DevServices support
* [*] Automatic and configurable reconnection handling and message redelivery
* [*] Real Health Check against a configurable topic (defaults to the standard MQTT $SYS/broker/uptime) integrated in Quarkus HealthReport
* [*] Many others you can read in official documentation https://hivemq.github.io/hivemq-mqtt-client/[here].
