name: "Pull Request CI"

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - '*.md'
      - '*.adoc'
      - '*.txt'
      - '.all-contributorsrc'

jobs:
  validate-format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11 ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        check-latest: true
    - name: format
      run: mvn -V -B formatter:validate verify -DskipTests -DskipITs
    - name: Tar Maven Repo
      shell: bash
      run: tar -I 'pigz -9' -cf maven-repo.tgz -C ~ .m2/repository
    - name: Persist Maven Repo
      uses: actions/upload-artifact@v3
      with:
        name: maven-repo
        path: maven-repo.tgz
  linux-build-jvm:
    name: PR - Linux - JVM build - Latest Version
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: validate-format
    strategy:
      matrix:
        java: [ 11 ]
    steps:
    - uses: actions/checkout@v4
    - name: Install JDK {{ matrix.java }}
      # Uses sha for added security since tags can be updated
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        check-latest: true
        cache: 'maven'
    - name: Download Maven Repo
      uses: actions/download-artifact@v4
      with:
        name: maven-repo
        path: .
    - name: Extract Maven Repo
      shell: bash
      run: tar -xzf maven-repo.tgz -C ~
    - name: Build with Maven
      run: mvn -V -B -am clean verify
  linux-build-native:
    name: PR - Linux - Native build - Latest Version
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: validate-format
    strategy:
      matrix:
        java: [ 11, 17 ]
        image: [ "ubi-quarkus-native-image:22.3-java17", "ubi-quarkus-mandrel:22.3-java17", "ubi-quarkus-graalvmce-builder-image:22.3-java17" ]
    steps:
    - uses: actions/checkout@v4
    - name: Install JDK {{ matrix.java }}
      # Uses sha for added security since tags can be updated
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        check-latest: true
        cache: 'maven'
    - name: Download Maven Repo
      uses: actions/download-artifact@v4
      with:
        name: maven-repo
        path: .
    - name: Extract Maven Repo
      shell: bash
      run: tar -xzf maven-repo.tgz -C ~
    - name: Build with Maven
      run: mvn -V -B -am clean verify -Dnative -Dquarkus.native.builder-image=quay.io/quarkus/${{ matrix.image }}

