name: Maven Dependency Submission
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  analyze:
    name: Analyze Code
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Debug Maven Version
        run: ./mvnw --version

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v4
        with:
          languages: java

      - name: Build Project
        run: ./mvnw clean install -DskipTests

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v4
