name: Maven Dependency Submission
on:
  workflow_dispatch:
  schedule:
    - cron: '30 0 * * *'

jobs:
  dependencies:
    name: Submit Dependencies
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: maven

      - name: Make mvnw executable
        run: chmod +x mvnw

      - name: Debug Maven Version
        run: ./mvnw --version

      - name: Build the Project
        run: mvn clean install -DskipTests

      - name: Collect and submit dependencies
        uses: advanced-security/maven-dependency-submission-action@v4
        with:
          directory: "."
          ignore-maven-wrapper: true
